# Generated by Django 4.0 on 2023-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notification_on',
            field=models.BooleanField(default=True),
        ),
    ]
