# Generated by Django 4.0 on 2023-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_is_notification_on'),
        ('notification', '0002_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='schedule_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to='account.user'),
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
